- test/test_init.py
This adds a test file for the init script and tests the failure condition - where the env var is missing. The other tests in our suite cover the inverse.
> Add test for __init__ file, resolves #36

- README.rst
- sparkpost/__init__.py
- sparkpost/transmissions.py
- test/test_transmissions.py
Renamed files to transmissions. Kept a reference to `self.transmission` in the `__init__.py`
Closes #34
> Renamed transmission to transmissions retaining backwards compatibility

- .gitignore
- AUTHORS.rst
- docs/api/templates.rst
- docs/index.rst
- docs/resources/templates.rst
- examples/templates/create_template.py
- examples/templates/delete_template.py
- examples/templates/get_template.py
- examples/templates/list_templates.py
- examples/templates/preview_draft_template.py
- examples/templates/preview_template.py
- examples/templates/update_template.py
- sparkpost/__init__.py
- sparkpost/templates.py
- test/test_templates.py
Closes #14.
@richleland: Please look over this. We can discuss it Monday. I want to make sure I'm doing everything appropriately before continuing on to the other resources.
> Added Templates resource lib

- docs/api.rst
- docs/index.rst
This uses the ``:glob:`` setting for the toctree so we don't have to manually edit these files. Just add resources and/or api files and they'll get auto-added.
> Use glob to match all files in resources and api folders

- docs/api/recipient_lists.rst
- docs/api/transmissions.rst
- docs/resources/recipient_lists.rst
- examples/recipient_lists/create_recipient_list.py
- examples/recipient_lists/delete_recipient_list.py
- examples/recipient_lists/get_recipient_list.py
- examples/recipient_lists/get_recipient_list_with_recipients.py
- examples/recipient_lists/list_recipient_lists.py
- examples/recipient_lists/update_recipient_list.py
- examples/templates/delete_template.py
- examples/templates/preview_draft_template.py
- examples/templates/preview_template.py
- sparkpost/__init__.py
- sparkpost/recipient_lists.py
- sparkpost/templates.py
- test/test_recipient_lists.py
Closes #12
Take a look and see if we want to abstract it any further. I left passing the recipients objects as is.
> Added Recipient Lists resource lib

- CHANGELOG.md
> add change log

- .editorconfig
- examples/recipient_lists/create_recipient_list.py
- examples/recipient_lists/delete_recipient_list.py
- examples/recipient_lists/get_recipient_list.py
- examples/recipient_lists/get_recipient_list_with_recipients.py
- examples/recipient_lists/list_recipient_lists.py
- examples/recipient_lists/update_recipient_list.py
- examples/suppression_list/create_suppression_entries_bulk.py
- examples/suppression_list/create_suppression_entry.py
- examples/suppression_list/delete_suppression_entry.py
- examples/suppression_list/get_suppression_entry.py
- examples/suppression_list/list_suppression_entries.py
- examples/suppression_list/update_suppression_entries_bulk.py
- examples/suppression_list/update_suppression_enty.py
- examples/templates/create_template.py
- examples/templates/delete_template.py
- examples/templates/get_template.py
- examples/templates/list_templates.py
- examples/templates/preview_draft_template.py
- examples/templates/preview_template.py
- examples/templates/update_template.py
- examples/transmissions/find_transmission.py
- examples/transmissions/get_transmissions.py
- examples/transmissions/send_transmission.py
- examples/transmissions/transmission_stored_list.py
- examples/transmissions/transmission_stored_template.py
- Resolves #51 
- Add editorconfig file
- Fixed some linting errors
> Remove YOUR API KEY references from examples

- docs/resources/transmissions.rst
- sparkpost/transmissions.py
- test/test_transmissions.py
This patch supports both passing a base64-encoded attachment or a filename, which will then be converted to base64. There is some ascii encoding done with the base64 to ensure compatibility between Python 2 and Python 3 (base64 in Python 3 returns a bytestring whereas Python 2 returns a string).
The tests ran successfully with Python 2.7 and Python 3.5.
> Added support for attachments. refs #56

- .travis.yml
- CONTRIBUTING.md
- dev-requirements.txt
- test-requirements.txt
- tox.ini
This pull request adds tox support, which I find very useful to test various combination of versions locally.
Some small additional changes:
1. I had to update the version of pytest to make it work with Python 3.5
2. I had to split the requirements file because tox install all dependencies at the same time, so it was complaining about the conflicting Django versions (one in dev-requirements.txt and one in tox.ini): I changed it so that all the other commands, e.g., make install or make test, should not be affected.
3. I updated the travis config to test the latest Django versions, e.g., Django 1.7.11 instead of Django 1.7
> Added tox support. refs #67

- sparkpost/transmissions.py
- test/test_transmissions.py
Adds support for emails with names (e.g. `Joe Smith <joesmith@example.com>`) for recipients.
> added email address parsing

- docs/resources/transmissions.rst
- examples/transmissions/send_transmission.py
- sparkpost/transmissions.py
- test/test_transmissions.py
- adds the ability to pass `cc` and/or `bcc` lists to the `send` method
- updates examples and docs
> Add support for cc/bcc

- docs/django/backend.rst
- sparkpost/django/email_backend.py
- test/django/test_email_backend.py
I talked to cfs on Slack about this, and found that the Django backend was lacking a way to set parameters like tracking before sending. I came up with the solution seen in this PR. The settings I set and tested can be seen below
```
SPARKPOST_OPTIONS = {
'track_opens': False,
'track_clicks': False,
'transactional': True,
}
```
Since I'm not really familiar with various use-cases for an email backend I thought I'd just put it up here now, and hopefully someone else will point out any issues.
> Use django settings to set send options

- README.rst
- docs/django/backend.rst
- sparkpost/django/email_backend.py
- sparkpost/django/message.py
- test/django/test_email_backend.py
- test/django/test_message.py
- test/django/utils.py
- Refactored to use a custom message class that just preps data for the API (`SparkPostMessage`)
- Added test utils file for the `at_least_version` function
- Was able to really simplify the backend code - most of the logic lives in the message class now
> Support for cc/bcc in Django backend

- sparkpost/django/message.py
- sparkpost/transmissions.py
- test/django/test_message.py
The API spec specifies attachments must be base64 encoded.  This fixes the SparkPostMessage class to actually base64 attachments as well as an invalid test to verify the data is actually encoded property.  This also deals with handling unicode attachments without UnicodeDecodeErrors
> fix Django backend to correctly base64 encode attachments

- AUTHORS.rst
- dev-requirements.txt
- sparkpost/__init__.py
- sparkpost/base.py
- sparkpost/django/message.py
- sparkpost/exceptions.py
- sparkpost/metrics.py
- sparkpost/tornado/__init__.py
- sparkpost/tornado/base.py
- sparkpost/tornado/exceptions.py
- sparkpost/tornado/transmissions.py
- sparkpost/tornado/utils.py
- sparkpost/transmissions.py
- test/test_base.py
- test/tornado/test_tornado.py
- test/tornado/utils.py
Updated the code to make it more extensible (easier subclassing, allows async transports) and then added support for tornado and its transport via AsyncHTTPClient
> More extensibility and Tornado integration

- sparkpost/transmissions.py
For example if message contains no html, an exception is raised : 
````
SparkPostAPIException: Call to https://api.sparkpost.com/api/v1/transmissions 
returned 422, errors:
required field is missing: content.inline_images requires content.html
````
> Transmissions: inline_images should not be set by default in content

- docs/django/backend.rst
- sparkpost/django/message.py
- test/django/test_message.py
changed SparkPostMessage class __init__ method so those parameters will be accepted now.
> Issue #107 -Django backend unable to use templates, substitution_data

- sparkpost/django/message.py
- test/django/test_message.py
Hello,
This is an issue I ran into while using [django-post-office](https://github.com/ui/django-post_office). The django `EmailMessage.attach` method does not require you to submit a mimetype, stating that it is [guessed if not provided](https://github.com/django/django/blob/master/django/core/mail/message.py#L303). Unfortunately the django-post-office API does not support specifying a mime type, meaning I have no choice but to rely on the guessing mechanism. Long story short, I cannot currently attach any files to my emails.
The email backend would normally let the EmailMessage class do this when converting the email to MIME format (see the `EmailMessage.message` [method](https://github.com/django/django/blob/master/django/core/mail/message.py#L259) which eventually calls …
> guess attachment mimetype in Django email backend if not provided

- sparkpost/exceptions.py
I needed the ability to determine when I should blacklist email addresses that were returning errors from SparkPost's REST API and I discovered that the [extended error code](https://support.sparkpost.com/customer/en/portal/articles/2140916-extended-error-codes) was already being returned so this change is simply to add that extended error code to the exception message so that downstream consumers can parse it out with something like
`p = re.compile(r'Code: (?P<code>\d+) ')`
`m = p.search(e_str)`
`codes = [int(c) for c in m.group('code')]`
> add extended error code to exception

- sparkpost/base.py
Requests will utilise HTTP Keep-Alive if multiple requests to the same hostname are within a 'Session' object. 
Source: http://docs.python-requests.org/en/master/user/advanced/
"Excellent news — thanks to urllib3, keep-alive is 100% automatic within a session! Any requests that you make within a session will automatically reuse the appropriate connection!"
This change makes the RequestsTransport open a session and reuse it for future requests. On our tests this gives significantly better throughput as a TCP / SSL  connection is not opened for each request.
> Make RequestsTransport use a requests session

- sparkpost/exceptions.py
- test/test_base.py
- test/test_transmissions.py
This PR does a few things:
* Fixes an issue reported in #134 related to handling of the error responses:
```
Traceback (most recent call last):
File "send_transmission.py", line 19, in <module>
campaign='python-sparkpost example',
File "/Users/rleland/src/oss/python-sparkpost/sparkpost/transmissions.py", line 248, in send
results = self.request('POST', self.uri, data=json.dumps(payload))
File "/Users/rleland/src/oss/python-sparkpost/sparkpost/base.py", line 41, in request
**kwargs)
File "/Users/rleland/src/oss/python-sparkpost/sparkpost/base.py", line 16, in request
raise SparkPostAPIException(response)
File "/Users/rleland/src/oss/python-sparkpost/sparkpost/exceptions.py", line 30, in __init__
errors='\n'.join(errors)
TypeError: sequence item 0: expected string, dict found
```
This was …
> Tweaks to exception handling

- sparkpost/django/message.py
- test/django/test_message.py
Updates sending a Django `EmailMessage` to support a `campaign` attribute. Also adds a test to verify.
Closes #136
> Update SparkPostMessage to support campaign

- sparkpost/transmissions.py
- test/test_transmissions.py
> Validate type of recipients

- Makefile
- sparkpost/transmissions.py
- test-requirements.txt
- test/test_transmissions.py
> allow sending params in transmission list endpoint

- sparkpost/transmissions.py
Fixing missing param documentation raised in #161. Also updated some of the other docs that had small errors.
> Add return_path param to send() docs

- README.rst
The `SparkPost__init__` expects the BASE URI without the /api
> Fix EU API base URI

- AUTHORS.rst
- README.rst
- test-requirements.txt
requests 2.20.0 was released in order to resolve a security issue. From http://docs.python-requests.org/en/master/community/updates/#release-history :
> Requests removes Authorization header from requests redirected from https to http on the same hostname. (CVE-2018-18074)
Update to requests 2.20.1 to pick up that security fix, plus other bugfixes.
This has the side effect that Python 2.6 is no longer supported, because requests >= 2.20.0 no longer supports Python 2.6.
> Require later release of requests, to pick up security fixes for CVE-2018-18074

- AUTHORS.rst
- README.rst
- docs/django/backend.rst
- sparkpost/__init__.py
- sparkpost/django/email_backend.py
- test/django/test_email_backend.py
The base URI can be specified in the Django settings module via `SPARKPOST_BASE_URI`.
> Allowing US or EU API to be used in the Django backend.

- sparkpost/transmissions.py
Reverts SparkPost/python-sparkpost#204
> Revert "Update transmissions.py"
